// The settings table of README.md, generated from config/defaults.json (npm run docs:agents), so the documented defaults never drift from the code.
import type { SettingRow } from "./settings";

export const SETTINGS_START = "<!-- settings:start (generated by npm run docs:agents from config/defaults.json - do not edit) -->";
export const SETTINGS_END = "<!-- settings:end -->";

const short = (v: unknown) => { const s = JSON.stringify(v); return s.length > 60 ? `${s.slice(0, 60)}…` : s; };

export function settingsTableBlock(defs: SettingRow[]): string {
  const rows = defs.map((d) => `| \`${d.key}\` | \`${short(d.value).replace(/\|/g, "\|")}\` | ${d.unit} | ${d.description.replace(/\|/g, "\|")} |`);
  return [SETTINGS_START, "| key | default | unit | description |", "|---|---|---|---|", ...rows, SETTINGS_END].join("\n");
}

export function replaceSettingsTable(doc: string, block: string): string | null {
  const a = doc.indexOf(SETTINGS_START), b = doc.indexOf(SETTINGS_END);
  if (a < 0 || b < a) return null;
  return doc.slice(0, a) + block + doc.slice(b + SETTINGS_END.length);
}
