// The agent tables of docs/ARCHITECTURE.md and README.md, generated from the registry and the locales (npm run docs:agents), so the docs never drift from the code.
import { REGISTRY } from "./registry";

export const TABLE_START = "<!-- agents:start (generated by npm run docs:agents - do not edit) -->";
export const TABLE_END = "<!-- agents:end -->";

/** The full generated block of the architecture document (markers included). `en` and `ar` are the locale files. */
export function agentTableBlock(en: Record<string, string>, ar: Record<string, string>): string {
  const code = (xs: readonly string[]) => xs.map((x) => `\`${x}\``).join(", ");
  const head = "| # | Agent (EN / AR) | Stage | Role | Reads | Writes | Runs (setting) | VERIFY (self-check) | File |\n|---|---|---|---|---|---|---|---|---|";
  const rows = REGISTRY.map((a) =>
    `| ${a.order} | **${en[`agent.${a.id}`]}** / ${ar[`agent.${a.id}`]} (\`${a.id}\`) | ${a.stage} | ${en[`agentdef.${a.id}.role`]} | ${code(a.reads)} | ${code(a.writes)} | \`${a.scheduleKey}\`${a.afterDecision ? " + after every decision" : ""} | ${a.verifies.map((v) => en[`vchk.${v}`]).join("; ")} | \`${a.file}\` |`);
  return [TABLE_START, head, ...rows, TABLE_END].join("\n");
}

/** The short table for the README (number, agent, role, schedule, code file). */
export function agentTableCompact(en: Record<string, string>, ar: Record<string, string>): string {
  const head = "| # | Agent (EN / AR) | What it does | Runs | Code |\n|---|---|---|---|---|";
  const rows = REGISTRY.map((a) => `| ${a.order} | **${en[`agent.${a.id}`]}** / ${ar[`agent.${a.id}`]} | ${en[`agentdef.${a.id}.role`]} | \`${a.scheduleKey}\` | [\`${a.file}\`](${a.file}) |`);
  return [TABLE_START, head, ...rows, TABLE_END].join("\n");
}

/** Replaces the generated block inside a document (or returns null when the markers are missing). */
export function replaceAgentTable(doc: string, block: string): string | null {
  const a = doc.indexOf(TABLE_START), b = doc.indexOf(TABLE_END);
  if (a < 0 || b < a) return null;
  return doc.slice(0, a) + block + doc.slice(b + TABLE_END.length);
}
