// npm run req:update — rewrites the "Project dependencies" block of req.txt from package.json and package-lock.json (never typed by hand).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const lock = JSON.parse(fs.readFileSync(path.join(root, "package-lock.json"), "utf8"));
const installed = (name) => lock.packages?.[`node_modules/${name}`]?.version ?? "?";
const engines = (name) => lock.packages?.[`node_modules/${name}`]?.engines?.node;
const line = (name, range) => `  ${name.padEnd(24)} ${installed(name).padEnd(10)} (package.json: ${range})${engines(name) ? `  needs Node ${engines(name)}` : ""}`;

const block = [
  "<<DEPS-START>> (generated by `npm run req:update` from package.json + package-lock.json)",
  `Project: ${pkg.name} ${pkg.version}   engines: node ${pkg.engines?.node}, npm ${pkg.engines?.npm}`,
  "",
  "Runtime packages:",
  ...Object.entries(pkg.dependencies ?? {}).map(([n, r]) => line(n, r)),
  "",
  "Development packages:",
  ...Object.entries(pkg.devDependencies ?? {}).map(([n, r]) => line(n, r)),
  "",
  `Total packages in the lock file (including sub-dependencies): ${Object.keys(lock.packages).length - 1}`,
  "<<DEPS-END>>",
].join("\n");

const file = path.join(root, "req.txt");
const txt = fs.readFileSync(file, "utf8");
const next = txt.replace(/<<DEPS-START>>[\s\S]*<<DEPS-END>>/, block);
if (next === txt && !txt.includes("<<DEPS-START>>")) { console.error("req.txt has no <<DEPS-START>> / <<DEPS-END>> markers"); process.exit(1); }
fs.writeFileSync(file, next);
console.log("req.txt dependency block updated.");
